### ISSUE TITLE
Use of weak cryptographic primitive,MEDIUM,HIGH

### ISSUE THREAD

**Issue by cyw3** [GoASTScanner/gas#148]
Question:
1. What is the meanning of warning "Use of weak cryptographic primitive,MEDIUM,HIGH"?

2. How to fix this warning?

3. Why are these in blacklist?

code：
import "crypto/md5"
func main(){
    h := md5.New()
}

**Comment by gcmurphy** [comment]
MD5 is no longer considered a 'secure hash' function for the purposes of security functionality due to a number of [security issues](https://en.wikipedia.org/wiki/MD5#Overview_of_security_issues).  

If it is a security sensitive functionality I would suggest migrating to something in alignment with the [NIST guidelines](https://csrc.nist.gov/Projects/Hash-Functions/NIST-Policy-on-Hash-Functions). If you consider the error you're seeing as a false positive you can annotate your code with a `// #nosec` comment or run gas with `-exclude=G401,G501` to disable these rules entirely.
